import { AntdRegistry } from "@ant-design/nextjs-registry";
import type { Metadata } from "next";
import "./globals.css";
import { Inter as FontSans } from "next/font/google";
import { cn, getMenu } from "@/lib/utils";
import { Footer } from "@/components/footer";
import Header from "@/components/Header";
import { Suspense } from "react";
import { headers } from "next/headers";
import Loading from "./loading";
import { isMobile } from "../lib/isMobile";

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const menu = await getMenu();
  const userAgent = headers().get("user-agent") || "";
  const isMobileDevice = isMobile(userAgent);
  return (
    <html lang="en">
      <body
        className={cn(
          "min-h-screen bg-background font-sans antialiased",
          fontSans.variable
        )}
      >
        <AntdRegistry>
          <Header menu={menu} isMobileDevice={isMobileDevice} />
          <Suspense fallback={<Loading />}>{children}</Suspense>
          <Footer />
        </AntdRegistry>
      </body>
    </html>
  );
}
